"use strict";(()=>{var e={};e.id=8610,e.ids=[8610],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},22245:(e,t,i)=>{i.a(e,async(e,a)=>{try{i.r(t),i.d(t,{originalPathname:()=>m,patchFetch:()=>l,requestAsyncStorage:()=>p,routeModule:()=>d,serverHooks:()=>v,staticGenerationAsyncStorage:()=>c});var r=i(49303),s=i(88716),n=i(60670),o=i(40214),u=e([o]);o=(u.then?(await u)():u)[0];let d=new r.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/revs/admin/invites/route",pathname:"/api/revs/admin/invites",filename:"route",bundlePath:"app/api/revs/admin/invites/route"},resolvedPagePath:"/Volumes/SSK SSD/GitHub/tjrmindbody_public/public-site/src/app/api/revs/admin/invites/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:p,staticGenerationAsyncStorage:c,serverHooks:v}=d,m="/api/revs/admin/invites/route";function l(){return(0,n.patchFetch)({serverHooks:v,staticGenerationAsyncStorage:c})}a()}catch(e){a(e)}})},40214:(e,t,i)=>{i.a(e,async(e,a)=>{try{i.r(t),i.d(t,{GET:()=>u,POST:()=>l,runtime:()=>d});var r=i(87070),s=i(18831),n=e([s]);s=(n.then?(await n)():n)[0];let d="nodejs";function o(e){let t=e.headers.get("x-revs-admin-token")||"";return!!process.env.REVS_ADMIN_TOKEN&&t===process.env.REVS_ADMIN_TOKEN}async function u(e){if(!o(e))return r.NextResponse.json({ok:!1,error:"Unauthorized"},{status:401});await (0,s.V9)();let t=(0,s.C$)(),i=await t.query(`
      select id, code, label, active, uses_remaining, expires_at, created_at, updated_at
      from revs_invites
      order by created_at desc, id desc
    `);return r.NextResponse.json({ok:!0,invites:i.rows})}async function l(e){if(!o(e))return r.NextResponse.json({ok:!1,error:"Unauthorized"},{status:401});let t=await e.json().catch(()=>null);if(await (0,s.V9)(),t?.action==="toggle"&&"number"==typeof t.id&&"boolean"==typeof t.active){let e=(0,s.C$)(),i=await e.query(`
        update revs_invites
        set active = $2, updated_at = now()
        where id = $1
        returning id, code, label, active, uses_remaining, expires_at, created_at, updated_at
      `,[t.id,t.active]);return i.rows[0]?r.NextResponse.json({ok:!0,invite:i.rows[0]}):r.NextResponse.json({ok:!1,error:"Invite not found."},{status:404})}if(!t?.code){if(t?.allowlistEmail){let e=await (0,s.Wb)({email:t.allowlistEmail,label:t.allowlistLabel||"",active:t.allowlistActive??!0});return r.NextResponse.json({ok:!0,allowlist:e})}return r.NextResponse.json({ok:!1,error:"Missing invite code."},{status:400})}let i=await (0,s.DN)({code:t.code,label:t.label||"",usesRemaining:t.usesRemaining??null,expiresAt:t.expiresAt??null});return r.NextResponse.json({ok:!0,invite:i})}a()}catch(e){a(e)}})}};var t=require("../../../../../webpack-runtime.js");t.C(e);var i=e=>t(t.s=e),a=t.X(0,[8948,5972,8831],()=>i(22245));module.exports=a})();