"use strict";(()=>{var e={};e.id=383,e.ids=[383],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},60638:(e,t,s)=>{s.a(e,async(e,r)=>{try{s.r(t),s.d(t,{originalPathname:()=>f,patchFetch:()=>d,requestAsyncStorage:()=>c,routeModule:()=>p,serverHooks:()=>m,staticGenerationAsyncStorage:()=>l});var n=s(49303),o=s(88716),a=s(60670),i=s(47527),u=e([i]);i=(u.then?(await u)():u)[0];let p=new n.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/revs/admin/concepts/route",pathname:"/api/revs/admin/concepts",filename:"route",bundlePath:"app/api/revs/admin/concepts/route"},resolvedPagePath:"/Volumes/SSK SSD/GitHub/tjrmindbody_public/public-site/src/app/api/revs/admin/concepts/route.ts",nextConfigOutput:"",userland:i}),{requestAsyncStorage:c,staticGenerationAsyncStorage:l,serverHooks:m}=p,f="/api/revs/admin/concepts/route";function d(){return(0,a.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:l})}r()}catch(e){r(e)}})},47527:(e,t,s)=>{s.a(e,async(e,r)=>{try{s.r(t),s.d(t,{GET:()=>u,POST:()=>d,runtime:()=>p});var n=s(87070),o=s(18831),a=e([o]);o=(a.then?(await a)():a)[0];let p="nodejs";function i(e){let t=e.headers.get("x-revs-admin-token")||"";return!!process.env.REVS_ADMIN_TOKEN&&t===process.env.REVS_ADMIN_TOKEN}async function u(e){if(!i(e))return n.NextResponse.json({ok:!1,error:"Unauthorized"},{status:401});await (0,o.V9)();let t=new URL(e.url).searchParams.get("conceptId");if(t){let e=await (0,o.JF)(Number(t));return n.NextResponse.json({ok:!0,variants:e})}let s=await (0,o.yN)();return n.NextResponse.json({ok:!0,concepts:s})}async function d(e){if(!i(e))return n.NextResponse.json({ok:!1,error:"Unauthorized"},{status:401});await (0,o.V9)();let t=await e.json().catch(()=>null);if(!t)return n.NextResponse.json({ok:!1,error:"Missing request body."},{status:400});if("delete"===t.action&&"number"==typeof t.id){let e=(0,o.C$)(),s=await e.query(`
        delete from revs_concepts
        where id = $1
        returning id, slug, title, summary, stage, status, sort_order, principles, audience_framings, formats, depths, prerequisites, pairs_with, evidence, accessibility_notes, published_at, created_at, updated_at
      `,[t.id]);return s.rows[0]?n.NextResponse.json({ok:!0,concept:s.rows[0]}):n.NextResponse.json({ok:!1,error:"Concept not found."},{status:404})}if("toggle"===t.action&&"number"==typeof t.id){if(!t.status)return n.NextResponse.json({ok:!1,error:"Missing status."},{status:400});let e=await (0,o.f2)({id:t.id,status:t.status});return e?n.NextResponse.json({ok:!0,concept:e}):n.NextResponse.json({ok:!1,error:"Concept not found."},{status:404})}if("variant"===t.kind){if("delete"===t.action&&"number"==typeof t.id){let e=await (0,o.k2)({id:t.id});return e?n.NextResponse.json({ok:!0,variant:e}):n.NextResponse.json({ok:!1,error:"Variant not found."},{status:404})}if("duplicate"===t.action&&"number"==typeof t.id){let e=(0,o.C$)(),s=(await e.query(`
          select id, concept_id, variant_key, audience, format, depth, stage, status, body, notes, sort_order, published_at, created_at, updated_at
          from revs_concept_variants
          where id = $1
          limit 1
        `,[t.id])).rows[0];if(!s)return n.NextResponse.json({ok:!1,error:"Variant not found."},{status:404});let r=await (0,o.JV)({conceptId:s.concept_id,variantKey:`${s.variant_key}-copy`,audience:s.audience,format:s.format,depth:s.depth,stage:s.stage,status:"draft",body:s.body,notes:s.notes,sortOrder:s.sort_order+1});return n.NextResponse.json({ok:!0,variant:r})}if(!t.conceptId||!t.variantKey||!t.title)return n.NextResponse.json({ok:!1,error:"Missing variant fields."},{status:400});let e=await (0,o.JV)({conceptId:t.conceptId,variantKey:t.variantKey,audience:t.audience,format:t.format,depth:t.depth,stage:t.stage,status:t.status,body:t.body,notes:t.notes,sortOrder:t.variantSortOrder});return n.NextResponse.json({ok:!0,variant:e})}if(!t.slug||!t.title)return n.NextResponse.json({ok:!1,error:"Missing concept slug or title."},{status:400});let s=await (0,o.mc)({slug:t.slug,title:t.title,summary:t.summary,stage:t.stage,status:t.status,sortOrder:t.sortOrder,audienceFramings:t.audienceFramings,principles:t.principles,formats:t.formats,depths:t.depths,prerequisites:t.prerequisites,pairsWith:t.pairsWith,evidence:t.evidence,accessibilityNotes:t.accessibilityNotes});return n.NextResponse.json({ok:!0,concept:s})}r()}catch(e){r(e)}})}};var t=require("../../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),r=t.X(0,[8948,5972,8831],()=>s(60638));module.exports=r})();