"use strict";(()=>{var e={};e.id=3703,e.ids=[3703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},784:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>y,requestAsyncStorage:()=>f,routeModule:()=>d,serverHooks:()=>m,staticGenerationAsyncStorage:()=>p});var n={};r.r(n),r.d(n,{GET:()=>c});var o=r(49303),a=r(88716),i=r(60670),l=r(55661),s=r(59150),u=r(60707);async function c(){let e=await {rules:[{userAgent:"*",allow:"/",disallow:["/admin","/api","/search","/search-index.json"]}],sitemap:(0,s.GR)("/sitemap.xml")},t=(0,u.resolveRouteData)(e,"robots");return new l.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let d=new o.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2FVolumes%2FSSK%20SSD%2FGitHub%2Ftjrmindbody_public%2Fpublic-site%2Fsrc%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:n}),{requestAsyncStorage:f,staticGenerationAsyncStorage:p,serverHooks:m}=d,g="/robots.txt/route";function y(){return(0,i.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:p})}},60707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return i},resolveRobots:function(){return o},resolveRouteData:function(){return l},resolveSitemap:function(){return a}});let n=r(91389);function o(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,n.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,n.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,n.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,n.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function a(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let o of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var n;r+=`<url>
<loc>${o.url}</loc>
`;let e=null==(n=o.alternates)?void 0:n.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(o.lastModified){let e=o.lastModified instanceof Date?o.lastModified.toISOString():o.lastModified;r+=`<lastmod>${e}</lastmod>
`}o.changeFrequency&&(r+=`<changefreq>${o.changeFrequency}</changefreq>
`),"number"==typeof o.priority&&(r+=`<priority>${o.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function i(e){return JSON.stringify(e)}function l(e,t){return"robots"===t?o(e):"sitemap"===t?a(e):"manifest"===t?i(e):""}},91389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function n(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return n}})},59150:(e,t,r)=>{r.d(t,{GR:()=>a,c9:()=>n});let n=new Date("2026-07-10T00:00:00Z"),o={name:"TJR Mind & Body",tagline:"Practical resilience coaching and education for people navigating pressure, burnout, chronic pain, disruption, and steady rebuilding.",url:process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3200",locale:"en-GB",twitter:"@tjrmindbody",defaultOgImage:"/og-default.png"};function a(e){let t=o.url.replace(/\/$/,"");return`${t}${e.startsWith("/")?e:`/${e}`}`}}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[8948,2518],()=>r(784));module.exports=n})();